[theme]
base = "light"
primaryColor = "#144E9E"
backgroundColor = "#EEF3F6"
secondaryBackgroundColor = "#E3EBF1"
textColor = "#0E2233"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
